import { writable } from "svelte/store";

export const currentDayStore = writable(0)

export const testData = [
	{ "name": "Emma", "tally": 32 },
	{ "name": "Ethan", "tally": 14 },
	{ "name": "Isabella", "tally": 70 },
	{ "name": "Jayden", "tally": -16 },
	{ "name": "Isabella", "tally": -59 },
	{ "name": "Noah", "tally": 19 },
	{ "name": "Mia", "tally": -37 },
	{ "name": "Will", "tally": -20 },
	{ "name": "Sam", "tally": -91 },
	{ "name": "Brittney", "tally": -98 }
]

export const realData = [
    {"name":"Hayley","tally":100},
    {"name":"Mina","tally":87},
    {"name":"Aaliyah","tally":-75},
    {"name":"Eliza","tally":100},
    {"name":"Caesar","tally":-53},
    {"name":"Audrey","tally":-21},
    {"name":"Christy","tally":-23},
    {"name":"Ezekiel","tally":34},
    {"name":"Graciela","tally":88},
    {"name":"Kallie","tally":70},
    {"name":"Heaven","tally":-38},
    {"name":"Marley","tally":5},
    {"name":"Connor","tally":-11},
    {"name":"Shad","tally":-54},
    {"name":"Alek","tally":7},
    {"name":"Marco","tally":83},
    {"name":"Haylie","tally":-9},
    {"name":"Keegan","tally":-14},
    {"name":"Brooke","tally":88},
    {"name":"Clotilde","tally":56},
    {"name":"Presley","tally":43},
    {"name":"Vivianne","tally":61},
    {"name":"Elyssa","tally":-82},
    {"name":"Mathilde","tally":4},
    {"name":"Selina","tally":73},
    {"name":"Soledad","tally":66},
    {"name":"Arvel","tally":66},
    {"name":"Alison","tally":-46},
    {"name":"Cecelia","tally":-89},
    {"name":"Shad","tally":34},
    {"name":"Ayden","tally":19},
    {"name":"Helene","tally":35},
    {"name":"Vernie","tally":-18},
    {"name":"Kacie","tally":-61},
    {"name":"Mathias","tally":-42},
    {"name":"Emerson","tally":-72},
    {"name":"Marques","tally":57},
    {"name":"Roberto","tally":-18},
    {"name":"Aida","tally":-94},
    {"name":"Neoma","tally":25},
    {"name":"Yasmin","tally":32},
    {"name":"Nelda","tally":-41},
    {"name":"Dwight","tally":-11},
    {"name":"Patience","tally":-56},
    {"name":"Beatrice","tally":-86},
    {"name":"Isaiah","tally":-6},
    {"name":"Sylvan","tally":-81},
    {"name":"Eldora","tally":81},
    {"name":"Eduardo","tally":-76},
    {"name":"Breana","tally":5},
    {"name":"Aimee","tally":-84},
    {"name":"Mariela","tally":84},
    {"name":"Cory","tally":83},
    {"name":"Dimitri","tally":-40},
    {"name":"Jerad","tally":17},
    {"name":"Amir","tally":13},
    {"name":"Kiley","tally":23},
    {"name":"Caden","tally":92},
    {"name":"Laisha","tally":-48},
    {"name":"Maximus","tally":-54},
    {"name":"Bartholome","tally":7},
    {"name":"Harry","tally":90},
    {"name":"Maud","tally":-1},
    {"name":"Harry","tally":8},
    {"name":"Amaya","tally":53},
    {"name":"Kailey","tally":-91},
    {"name":"Malcolm","tally":-72},
    {"name":"Jordon","tally":59},
    {"name":"Tyrel","tally":-95},
    {"name":"Kyler","tally":77},
    {"name":"Stewart","tally":8},
    {"name":"Brionna","tally":-10},
    {"name":"Broderick","tally":79},
    {"name":"Rafael","tally":-25},
    {"name":"Grant","tally":8},
    {"name":"Casper","tally":31},
    {"name":"Timmy","tally":-28},
    {"name":"Fanny","tally":14},
    {"name":"Nettie","tally":28},
    {"name":"Moises","tally":-75},
    {"name":"Shaun","tally":38},
    {"name":"Lindsay","tally":30},
    {"name":"Nettie","tally":-29},
    {"name":"Fausto","tally":53},
    {"name":"Dominique","tally":-29},
    {"name":"Sonya","tally":51},
    {"name":"Hilbert","tally":77},
    {"name":"Violette","tally":-98},
    {"name":"Malachi","tally":0},
    {"name":"Lilly","tally":-86},
    {"name":"Bethel","tally":58},
    {"name":"Vada","tally":-88},
    {"name":"Israel","tally":-29},
    {"name":"Kolby","tally":89},
    {"name":"Hailey","tally":-24},
    {"name":"Dasia","tally":53},
    {"name":"Stewart","tally":55},
    {"name":"Kiera","tally":-40},
    {"name":"Abdul","tally":55},
    {"name":"Lexus","tally":-70}
]